# Generated by Django 3.2.7 on 2022-10-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hngprofile',
            name='username',
            field=models.CharField(max_length=200, verbose_name='slackUsername'),
        ),
    ]
