# Generated by Django 3.2.7 on 2022-10-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_hngprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hngprofile',
            old_name='username',
            new_name='slackUsername',
        ),
    ]
